### ISSUE TITLE
KeyboardInteractive_PasswordExpired fails and corrupts container state

### ISSUE THREAD

**Issue by IgorMilavec** [sshnet/IntegrationTests#2]
```KeyboardInteractive_PasswordExpired``` fails on my container with:
```
Assert.AreEqual failed. Expected:<0>. Actual:<1>. passwd: unrecognized option: expire
BusyBox v1.34.1 (2021-11-23 00:57:35 UTC) multi-call binary.

Usage: passwd [-a ALG] [-dlu] [USER]

Change USER's password (default: current user)

	-a ALG	des,md5,sha256/512 (default sha512)
	-d	Set password to ''
	-l	Lock (disable) account
	-u	Unlock (enable) account
```
Additionally, this leaves the sshuser with a random password. To avoid this, we should:
 - reset the password in the TestInitialize phase
 - reset the password in catch block in KeyboardInteractive_PasswordExpired
I think this way regardless if the tests are interrupted we will return to the defined state.

I can try to fix this if you want?

**Comment by IgorMilavec** [comment]
Fix for missing --expire in alpine: https://stackoverflow.com/questions/57584867/alpine-linux-how-to-enforce-user-to-change-the-password-on-next-login

**Comment by drieseng** [comment]
@IgorMilavec I'll have a look at this.
